config/routes.rb
Rails.application.routes.draw do

  constraints Clearance::Constraints::SignedIn.new do
    root to: "dashboards#show", as: :signed_in_root
    resources :callbacks, only: :new
    resources :events do
      resource :activation, only: [:create]
      resource :deactivation, only: [:create]
    end
  end
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :attendees

  delegate :eventbrite_token, to: :user, prefix: false

  validates :name, presence: true

  def activate!
    update(active: true)
  end

  def deactivate!
    update(active: false)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :events
end

app/controllers/activations_controller.rb
class ActivationsController < ApplicationController
  def create
    @event = current_user.events.find(params[:event_id])
    @event.activate!

    AttendeeFetcherJob.perform_later(@event)

    redirect_to :back
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/callbacks_controller.rb
class CallbacksController < ApplicationController
  before_action :require_login

  def new
    if params[:code].nil?
      return redirect_with_failure
    end

    token = exchange_token(params[:code])

    unless token
      return redirect_with_failure
    end

    current_user.update(eventbrite_token: token)

    EventFetcherJob.perform_later(current_user)

    redirect_with_success
  end

  private

  def exchange_token(token)
    client = OAuth2::Client.new(
      ENV.fetch("EVENTBRITE_OAUTH_ID"),
      ENV.fetch("EVENTBRITE_OAUTH_SECRET"),
      site: "https://www.eventbrite.com/oauth/authorize"
    )

    begin
      client.auth_code.get_token(token, redirect_uri: new_callback_url).token
    rescue OAuth2::Error
      false
    end
  end

  def redirect_with_success
    redirect_to signed_in_root_path, notice: t("eventbrite_success")
  end

  def redirect_with_failure
    redirect_to signed_in_root_path, alert: t("eventbrite_failure")
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :require_login

  def show
    unless current_user.eventbrite_token?
      @eventbrite_auth_url = eventbrite_auth_url
    end

    @events = current_user.events.all
  end

  private

  def eventbrite_auth_url
    client ||= OAuth2::Client.new(
      ENV.fetch("EVENTBRITE_OAUTH_ID"),
      ENV.fetch("EVENTBRITE_OAUTH_SECRET"),
      site: "https://www.eventbrite.com/oauth/authorize"
    )

    client.auth_code.authorize_url(redirect_uri: new_callback_url)
  end
end

app/controllers/deactivations_controller.rb
class DeactivationsController < ApplicationController
  def create
    @event = current_user.events.find(params[:event_id])
    @event.deactivate!

    redirect_to :back
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login

  def index
    @events = current_user.events.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/admin/oauths/callback.html.erb
<h1>Successfully Connected to Eventbrite</h1>

<p>Your account has been successfully connected to Eventbrite.</p>

app/views/admin/oauths/show.html.erb
<h1>Connect to EventBrite</h1>

<p>We need to connect to EventBrite so that we can retrieve event and attendee data on your behalf.</p>

<p>Please click the button below and you will be redirect to EventBrite.</p>

<p><%= link_to "Connect to EventBrite", @authorization_url %></p>

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_sign_in_state.html.erb
<% if signed_in? %>
  Signed in as: <%= current_user.email %>
  <%= button_to 'Sign out', sign_out_path, method: :delete %>
<% else %>
  <%= link_to 'Sign in', sign_in_path %>
<% end %>

app/views/dashboards/show.html.erb
<h1>Dashboard</h1>

<% if @eventbrite_auth_url %>
  <%= link_to "Connect to Eventbrite", @eventbrite_auth_url %>
<% end %>

<ul class="events">
  <% @events.each do |event| %>
    <li data-id="<%= event.id %>">
      <%= event.name %>
      <% if event.active? %>
        <%= link_to "Deactivate", event_deactivation_path(event), method: :post %>
      <% else %>
        <%= link_to "Activate", event_activation_path(event), method: :post %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/events/edit.html.erb
<h1><%= t('event.update') %></h1>
<%= render 'form' %>

app/views/events/index.html.erb
<p><%= link_to t("event.add"), new_event_path %></p>

<table class="events">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr data-id="<%= event.id %>">
        <td><%= event.name %></td>
        <td><%= link_to t("shared.edit"), edit_event_path(event) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h1><%= t('event.create') %></h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "sign_in_state" %>
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Gatwick</h1>
<h2>Self-Service Check-In for EventBrite Events</h2>

<p class="cta"><%= link_to "Sign Up", sign_up_path %></p>